//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
// @ts-nocheck

// ISO 8601 date string pattern for JSON reviver
const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?$/;

/**
 * JSON parse reviver that converts ISO date strings to Date objects.
 * This is needed because when using interface-based types (after NSwag migration),
 * dates are not automatically converted from strings to Date objects.
 */
function dateReviver(key: string, value: unknown): unknown {
  if (typeof value === "string" && ISO_DATE_PATTERN.test(value)) {
    const date = new Date(value);
    // Only return Date if it's valid
    if (!isNaN(date.getTime())) {
      return date;
    }
  }
  return value;
}

export class AuthApiBase {
  authToken = "";

  /**
   * JSON parse reviver for converting date strings to Date objects.
   * Subclasses use this when parsing API responses.
   * The dateReviver function is defined in File.Header.liquid template.
   */
  protected jsonParseReviver = dateReviver;

  protected constructor() {}

  // Enforce always return empty string as baseUrl
  getBaseUrl(defaultUrl: string, baseUrl: string) {
    return "";
  }

  setAuthToken(token: string) {
    this.authToken = token;
  }

  protected transformOptions(options: any): Promise<any> {
    if (this.authToken) {
      options.headers["authorization"] = `Bearer ${this.authToken}`;
    }
    return Promise.resolve(options);
  }
}

export class StateMachineClient extends AuthApiBase {
  private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
  private baseUrl: string;

  constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
    super();
    this.http = http ? http : (window as any);
    this.baseUrl = this.getBaseUrl("", baseUrl);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  search(body?: SearchStateMachineDefinitionsQuery | undefined): Promise<SearchStateMachineDefinitionResult> {
    let url_ = this.baseUrl + "/api/statemachine/definitions/search";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processSearch(_response);
      });
  }

  protected processSearch(response: Response): Promise<SearchStateMachineDefinitionResult> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(_responseText, this.jsonParseReviver) as SearchStateMachineDefinitionResult);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<SearchStateMachineDefinitionResult>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  createNewDefinition(body?: CreateStateMachineDefinitionCommand | undefined): Promise<StateMachineDefinition> {
    let url_ = this.baseUrl + "/api/statemachine/definitions/new";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processCreateNewDefinition(_response);
      });
  }

  protected processCreateNewDefinition(response: Response): Promise<StateMachineDefinition> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as StateMachineDefinition);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<StateMachineDefinition>(null as any);
  }

  /**
   * @return OK
   */
  getStateMachineById(definitionId: string): Promise<StateMachineDefinition> {
    let url_ = this.baseUrl + "/api/statemachine/definitions/{definitionId}";
    if (definitionId === undefined || definitionId === null)
      throw new globalThis.Error("The parameter 'definitionId' must be defined.");
    url_ = url_.replace("{definitionId}", encodeURIComponent("" + definitionId));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processGetStateMachineById(_response);
      });
  }

  protected processGetStateMachineById(response: Response): Promise<StateMachineDefinition> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as StateMachineDefinition);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<StateMachineDefinition>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  validateDefinition(body?: StateMachineDefinition | undefined): Promise<StateMachineDefinition> {
    let url_ = this.baseUrl + "/api/statemachine/definitions/validate";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processValidateDefinition(_response);
      });
  }

  protected processValidateDefinition(response: Response): Promise<StateMachineDefinition> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as StateMachineDefinition);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<StateMachineDefinition>(null as any);
  }

  /**
   * @param entityType (optional)
   * @param locale (optional)
   * @return OK
   */
  getAllStates(entityType?: string | undefined, locale?: string | undefined): Promise<StateMachineStateShort[]> {
    let url_ = this.baseUrl + "/api/statemachine/definitions/allstates?";
    if (entityType === null) throw new globalThis.Error("The parameter 'entityType' cannot be null.");
    else if (entityType !== undefined) url_ += "entityType=" + encodeURIComponent("" + entityType) + "&";
    if (locale === null) throw new globalThis.Error("The parameter 'locale' cannot be null.");
    else if (locale !== undefined) url_ += "locale=" + encodeURIComponent("" + locale) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processGetAllStates(_response);
      });
  }

  protected processGetAllStates(response: Response): Promise<StateMachineStateShort[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as StateMachineStateShort[]);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<StateMachineStateShort[]>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  searchInstance(body?: SearchStateMachineInstancesQuery | undefined): Promise<SearchStateMachineInstanceResult> {
    let url_ = this.baseUrl + "/api/statemachine/instances/search";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processSearchInstance(_response);
      });
  }

  protected processSearchInstance(response: Response): Promise<SearchStateMachineInstanceResult> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(_responseText, this.jsonParseReviver) as SearchStateMachineInstanceResult);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<SearchStateMachineInstanceResult>(null as any);
  }

  /**
   * @return OK
   */
  getStateMachineInstanceById(instanceId: string): Promise<StateMachineInstance> {
    let url_ = this.baseUrl + "/api/statemachine/instances/{instanceId}";
    if (instanceId === undefined || instanceId === null)
      throw new globalThis.Error("The parameter 'instanceId' must be defined.");
    url_ = url_.replace("{instanceId}", encodeURIComponent("" + instanceId));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processGetStateMachineInstanceById(_response);
      });
  }

  protected processGetStateMachineInstanceById(response: Response): Promise<StateMachineInstance> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as StateMachineInstance);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<StateMachineInstance>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  getStateMachineForEntity(body?: GetStateMachineInstanceForEntityQuery | undefined): Promise<StateMachineInstance> {
    let url_ = this.baseUrl + "/api/statemachine/instances/entity";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processGetStateMachineForEntity(_response);
      });
  }

  protected processGetStateMachineForEntity(response: Response): Promise<StateMachineInstance> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as StateMachineInstance);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<StateMachineInstance>(null as any);
  }

  /**
   * @param instanceId (optional)
   * @param body (optional)
   * @return OK
   */
  createNewInstance(
    definitionId: string,
    instanceId?: string | undefined,
    body?: IHasDynamicProperties | undefined,
  ): Promise<StateMachineInstance> {
    let url_ = this.baseUrl + "/api/statemachine/instances/{definitionId}/new?";
    if (definitionId === undefined || definitionId === null)
      throw new globalThis.Error("The parameter 'definitionId' must be defined.");
    url_ = url_.replace("{definitionId}", encodeURIComponent("" + definitionId));
    if (instanceId === null) throw new globalThis.Error("The parameter 'instanceId' cannot be null.");
    else if (instanceId !== undefined) url_ += "instanceId=" + encodeURIComponent("" + instanceId) + "&";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processCreateNewInstance(_response);
      });
  }

  protected processCreateNewInstance(response: Response): Promise<StateMachineInstance> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as StateMachineInstance);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<StateMachineInstance>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  fireTrigger(body?: FireStateMachineTriggerCommand | undefined): Promise<StateMachineInstance> {
    let url_ = this.baseUrl + "/api/statemachine/firetrigger";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processFireTrigger(_response);
      });
  }

  protected processFireTrigger(response: Response): Promise<StateMachineInstance> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as StateMachineInstance);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<StateMachineInstance>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  searchLocalization(
    body?: SearchStateMachineLocalizationsQuery | undefined,
  ): Promise<SearchStateMachineLocalizationResult> {
    let url_ = this.baseUrl + "/api/statemachine/localization/search";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processSearchLocalization(_response);
      });
  }

  protected processSearchLocalization(response: Response): Promise<SearchStateMachineLocalizationResult> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(_responseText, this.jsonParseReviver) as SearchStateMachineLocalizationResult);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<SearchStateMachineLocalizationResult>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  updateLocalization(body?: UpdateStateMachineLocalizationCommand | undefined): Promise<void> {
    let url_ = this.baseUrl + "/api/statemachine/localization/update";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processUpdateLocalization(_response);
      });
  }

  protected processUpdateLocalization(response: Response): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        return;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  searchAttribute(body?: SearchStateMachineAttributesQuery | undefined): Promise<SearchStateMachineAttributeResult> {
    let url_ = this.baseUrl + "/api/statemachine/attribute/search";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processSearchAttribute(_response);
      });
  }

  protected processSearchAttribute(response: Response): Promise<SearchStateMachineAttributeResult> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(_responseText, this.jsonParseReviver) as SearchStateMachineAttributeResult);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<SearchStateMachineAttributeResult>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  updateAttribute(body?: UpdateStateMachineAttributeCommand | undefined): Promise<void> {
    let url_ = this.baseUrl + "/api/statemachine/attribute/update";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processUpdateAttribute(_response);
      });
  }

  protected processUpdateAttribute(response: Response): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        return;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  getSettings(): Promise<StateMachineSettings> {
    let url_ = this.baseUrl + "/api/statemachine/settings";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processGetSettings(_response);
      });
  }

  protected processGetSettings(response: Response): Promise<StateMachineSettings> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as StateMachineSettings);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<StateMachineSettings>(null as any);
  }
}

export interface Claim {
  issuer?: string | undefined;
  originalIssuer?: string | undefined;
  readonly properties?: { [key: string]: string } | undefined;
  subject?: ClaimsIdentity | undefined;
  type?: string | undefined;
  value?: string | undefined;
  valueType?: string | undefined;
}

export interface ClaimsIdentity {
  authenticationType?: string | undefined;
  readonly isAuthenticated?: boolean;
  actor?: ClaimsIdentity | undefined;
  bootstrapContext?: any | undefined;
  claims?: Claim[] | undefined;
  label?: string | undefined;
  readonly name?: string | undefined;
  readonly nameClaimType?: string | undefined;
  readonly roleClaimType?: string | undefined;
}

export interface ClaimsPrincipal {
  readonly claims?: Claim[] | undefined;
  identities?: ClaimsIdentity[] | undefined;
  identity?: IIdentity | undefined;
}

export interface CreateStateMachineDefinitionCommand {
  definition?: StateMachineDefinition | undefined;
}

export interface DynamicObjectProperty {
  objectId?: string | undefined;
  values?: DynamicPropertyObjectValue[] | undefined;
  name?: string | undefined;
  description?: string | undefined;
  objectType?: string | undefined;
  isArray?: boolean;
  isDictionary?: boolean;
  isMultilingual?: boolean;
  isRequired?: boolean;
  displayOrder?: number | undefined;
  valueType?: DynamicPropertyValueType;
  displayNames?: DynamicPropertyName[] | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface DynamicPropertyName {
  locale?: string | undefined;
  name?: string | undefined;
}

export interface DynamicPropertyObjectValue {
  objectType?: string | undefined;
  objectId?: string | undefined;
  locale?: string | undefined;
  value?: any | undefined;
  valueId?: string | undefined;
  valueType?: DynamicPropertyValueType;
  propertyId?: string | undefined;
  propertyName?: string | undefined;
}

export enum DynamicPropertyValueType {
  Undefined = "Undefined",
  ShortText = "ShortText",
  LongText = "LongText",
  Integer = "Integer",
  Decimal = "Decimal",
  DateTime = "DateTime",
  Boolean = "Boolean",
  Html = "Html",
  Image = "Image",
}

export interface FireStateMachineTriggerCommand {
  stateMachineInstanceId?: string | undefined;
  trigger?: string | undefined;
  entityId?: string | undefined;
  entityType?: string | undefined;
  user?: ClaimsPrincipal | undefined;
  locale?: string | undefined;
}

export interface GetStateMachineInstanceForEntityQuery {
  entityId: string;
  entityType: string;
  user?: ClaimsPrincipal | undefined;
  locale?: string | undefined;
}

export interface IConditionTree {
  readonly id?: string | undefined;
  /** List of all available children for current tree node (is used in expression designer) */
  readonly availableChildren?: IConditionTree[] | undefined;
  readonly children?: IConditionTree[] | undefined;
}

export interface IHasDynamicProperties {
  readonly objectType?: string | undefined;
  dynamicProperties?: DynamicObjectProperty[] | undefined;
  id?: string | undefined;
}

export interface IIdentity {
  readonly name?: string | undefined;
  readonly authenticationType?: string | undefined;
  readonly isAuthenticated?: boolean;
}

export interface SearchStateMachineAttributeResult {
  totalCount?: number;
  results?: StateMachineAttribute[] | undefined;
}

export interface SearchStateMachineAttributesQuery {
  definitionId?: string | undefined;
  definitionIds?: string[] | undefined;
  item?: string | undefined;
  attributeKey?: string | undefined;
  responseGroup?: string | undefined;
  objectType?: string | undefined;
  objectTypes?: string[] | undefined;
  objectIds?: string[] | undefined;
  keyword?: string | undefined;
  searchPhrase?: string | undefined;
  languageCode?: string | undefined;
  sort?: string | undefined;
  readonly sortInfos?: SortInfo[] | undefined;
  skip?: number;
  take?: number;
}

export interface SearchStateMachineDefinitionResult {
  totalCount?: number;
  results?: StateMachineDefinition[] | undefined;
}

export interface SearchStateMachineDefinitionsQuery {
  locale?: string | undefined;
  isActive?: boolean | undefined;
  responseGroup?: string | undefined;
  objectType?: string | undefined;
  objectTypes?: string[] | undefined;
  objectIds?: string[] | undefined;
  keyword?: string | undefined;
  searchPhrase?: string | undefined;
  languageCode?: string | undefined;
  sort?: string | undefined;
  readonly sortInfos?: SortInfo[] | undefined;
  skip?: number;
  take?: number;
}

export interface SearchStateMachineInstanceResult {
  totalCount?: number;
  results?: StateMachineInstance[] | undefined;
}

export interface SearchStateMachineInstancesQuery {
  locale?: string | undefined;
  responseGroup?: string | undefined;
  objectType?: string | undefined;
  objectTypes?: string[] | undefined;
  objectIds?: string[] | undefined;
  keyword?: string | undefined;
  searchPhrase?: string | undefined;
  languageCode?: string | undefined;
  sort?: string | undefined;
  readonly sortInfos?: SortInfo[] | undefined;
  skip?: number;
  take?: number;
}

export interface SearchStateMachineLocalizationResult {
  totalCount?: number;
  results?: StateMachineLocalization[] | undefined;
}

export interface SearchStateMachineLocalizationsQuery {
  definitionId?: string | undefined;
  definitionIds?: string[] | undefined;
  item?: string | undefined;
  locale?: string | undefined;
  responseGroup?: string | undefined;
  objectType?: string | undefined;
  objectTypes?: string[] | undefined;
  objectIds?: string[] | undefined;
  keyword?: string | undefined;
  searchPhrase?: string | undefined;
  languageCode?: string | undefined;
  sort?: string | undefined;
  readonly sortInfos?: SortInfo[] | undefined;
  skip?: number;
  take?: number;
}

export enum SortDirection {
  Ascending = "Ascending",
  Descending = "Descending",
}

export interface SortInfo {
  sortColumn?: string | undefined;
  sortDirection?: SortDirection;
}

export interface StateMachineAttribute {
  definitionId?: string | undefined;
  item?: string | undefined;
  attributeKey?: string | undefined;
  value?: string | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface StateMachineDefinition {
  version?: string | undefined;
  entityType?: string | undefined;
  name?: string | undefined;
  isActive?: boolean;
  states?: StateMachineState[] | undefined;
  statesGraph?: string | undefined;
  statesCapture?: string | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface StateMachineInstance {
  entityId?: string | undefined;
  entityType?: string | undefined;
  readonly stateMachineDefinitionId?: string | undefined;
  readonly stateMachineName?: string | undefined;
  readonly currentStateName?: string | undefined;
  readonly currentState?: StateMachineState | undefined;
  permittedTriggers?: string[] | undefined;
  readonly isActive?: boolean;
  stateMachineDefinition?: StateMachineDefinition | undefined;
  isStopped?: boolean;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface StateMachineLocalization {
  definitionId?: string | undefined;
  item?: string | undefined;
  locale?: string | undefined;
  value?: string | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface StateMachineSettings {
  languages?: string[] | undefined;
  attributeKeys?: string[] | undefined;
}

export interface StateMachineState {
  name?: string | undefined;
  type?: string | undefined;
  description?: string | undefined;
  isInitial?: boolean;
  isFinal?: boolean;
  isSuccess?: boolean;
  isFailed?: boolean;
  stateData?: any | undefined;
  localizedValue?: string | undefined;
  transitions?: StateMachineTransition[] | undefined;
  attributes?: StateMachineAttribute[] | undefined;
}

export interface StateMachineStateShort {
  name?: string | undefined;
  localizedValue?: string | undefined;
  description?: string | undefined;
  isInitial?: boolean;
  isFinal?: boolean;
  isSuccess?: boolean;
  isFailed?: boolean;
}

export interface StateMachineTransition {
  trigger?: string | undefined;
  description?: string | undefined;
  toState?: string | undefined;
  readonly icon?: string | undefined;
  localizedValue?: string | undefined;
  condition?: IConditionTree | undefined;
  attributes?: StateMachineAttribute[] | undefined;
}

export interface UpdateStateMachineAttributeCommand {
  attributes: StateMachineAttribute[];
}

export interface UpdateStateMachineLocalizationCommand {
  localizations: StateMachineLocalization[];
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(message: string, status: number, response: string, headers: { [key: string]: any }, result: any) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) throw result;
  else throw new ApiException(message, status, response, headers, null);
}

/* eslint-disable */
