//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
// @ts-nocheck

// ISO 8601 date string pattern for JSON reviver
const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?$/;

/**
 * JSON parse reviver that converts ISO date strings to Date objects.
 * This is needed because when using interface-based types (after NSwag migration),
 * dates are not automatically converted from strings to Date objects.
 */
function dateReviver(key: string, value: unknown): unknown {
  if (typeof value === "string" && ISO_DATE_PATTERN.test(value)) {
    const date = new Date(value);
    // Only return Date if it's valid
    if (!isNaN(date.getTime())) {
      return date;
    }
  }
  return value;
}

export class AuthApiBase {
  authToken = "";

  /**
   * JSON parse reviver for converting date strings to Date objects.
   * Subclasses use this when parsing API responses.
   * The dateReviver function is defined in File.Header.liquid template.
   */
  protected jsonParseReviver = dateReviver;

  protected constructor() {}

  // Enforce always return empty string as baseUrl
  getBaseUrl(defaultUrl: string, baseUrl: string) {
    return "";
  }

  setAuthToken(token: string) {
    this.authToken = token;
  }

  protected transformOptions(options: any): Promise<any> {
    if (this.authToken) {
      options.headers["authorization"] = `Bearer ${this.authToken}`;
    }
    return Promise.resolve(options);
  }
}

export class VcmpQuoteClient extends AuthApiBase {
  private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
  private baseUrl: string;

  constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
    super();
    this.http = http ? http : (window as any);
    this.baseUrl = this.getBaseUrl("", baseUrl);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  search(body?: SearchQuoteRequestsQuery | undefined): Promise<QuoteRequestSearchResult> {
    let url_ = this.baseUrl + "/api/vcmp/quote/search";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processSearch(_response);
      });
  }

  protected processSearch(response: Response): Promise<QuoteRequestSearchResult> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as QuoteRequestSearchResult);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<QuoteRequestSearchResult>(null as any);
  }

  /**
   * @param id (optional)
   * @return OK
   */
  getById(id?: string | undefined): Promise<VcmpQuoteRequest> {
    let url_ = this.baseUrl + "/api/vcmp/quote/getbyid?";
    if (id === null) throw new globalThis.Error("The parameter 'id' cannot be null.");
    else if (id !== undefined) url_ += "id=" + encodeURIComponent("" + id) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processGetById(_response);
      });
  }

  protected processGetById(response: Response): Promise<VcmpQuoteRequest> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as VcmpQuoteRequest);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<VcmpQuoteRequest>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  calculateTotals(body?: QuoteRequest | undefined): Promise<QuoteRequest> {
    let url_ = this.baseUrl + "/api/vcmp/quote/calculatetotals";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processCalculateTotals(_response);
      });
  }

  protected processCalculateTotals(response: Response): Promise<QuoteRequest> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 = _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as QuoteRequest);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<QuoteRequest>(null as any);
  }

  /**
   * @param body (optional)
   * @return No Content
   */
  update(body?: QuoteRequest | undefined): Promise<void> {
    let url_ = this.baseUrl + "/api/vcmp/quote/update";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processUpdate(_response);
      });
  }

  protected processUpdate(response: Response): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 204) {
      return response.text().then((_responseText) => {
        return;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  getConditionPrototype(): Promise<QuoteRequestCondition> {
    let url_ = this.baseUrl + "/api/vcmp/quote/condition/prototype";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processGetConditionPrototype(_response);
      });
  }

  protected processGetConditionPrototype(response: Response): Promise<QuoteRequestCondition> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as QuoteRequestCondition);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<QuoteRequestCondition>(null as any);
  }
}

export enum AddressType {
  Undefined = "Undefined",
  Billing = "Billing",
  Shipping = "Shipping",
  BillingAndShipping = "BillingAndShipping",
  Pickup = "Pickup",
}

export interface Asset {
  mimeType?: string | undefined;
  size?: number;
  readonly readableSize?: string | undefined;
  binaryData?: string | undefined;
  relativeUrl?: string | undefined;
  url?: string | undefined;
  description?: string | undefined;
  sortOrder?: number;
  /** Gets or sets the asset type identifier. */
  typeId?: string | undefined;
  /** Gets or sets the asset group name. */
  group?: string | undefined;
  /** Gets or sets the asset name. */
  name?: string | undefined;
  outerId?: string | undefined;
  /** Gets or sets the asset language. */
  languageCode?: string | undefined;
  /** System flag used to mark that object was inherited from other */
  readonly isInherited?: boolean;
  readonly seoObjectType?: string | undefined;
  seoInfos?: SeoInfo[] | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface CatalogProduct {
  /** The type of product. Can be "Physical", "Digital", etc. */
  productType?: string | undefined;
  /** The Stock Keeping Unit (SKU) code for the product. */
  code?: string | undefined;
  /** A manufacturer part number (MPN) is a unique alphanumeric code assigned by a manufacturer to identify a specific product or component. It is used primarily for part tracking in inventory management, supply chain operations, and ordering purposes. */
  manufacturerPartNumber?: string | undefined;
  /** The Global Trade Item Number (GTIN) for the product. This can include UPC (in North America), EAN (in Europe), JAN (in Japan), and ISBN (for books). */
  gtin?: string | undefined;
  /** The name of the product. */
  name?: string | undefined;
  localizedName?: LocalizedString | undefined;
  /** The ID of the catalog to which this product belongs. */
  catalogId?: string | undefined;
  /** The ID of the category to which this product belongs. */
  categoryId?: string | undefined;
  /** Product outline in physical catalog (all parent categories ids concatenated. E.g. (1/21/344)) */
  readonly outline?: string | undefined;
  /** Product path in physical catalog (all parent categories names concatenated. E.g. (parent1/parent2)) */
  readonly path?: string | undefined;
  readonly titularItemId?: string | undefined;
  /** The ID of the main product associated with this product variation. */
  mainProductId?: string | undefined;
  /** Specifies whether the product is currently visible on the store for customers to view and purchase.
If set to false, the product is currently sold out. */
  isActive?: boolean | undefined;
  /** Specifies whether the product is currently visible on the store for customers to view and purchase.
If set to false, the product is currently ouf of stock. */
  isBuyable?: boolean | undefined;
  /** Indicates whether the inventory service is tracking the availability of this product.
If set to false, the product is considered in stock without any inventory limitations. */
  trackInventory?: boolean | undefined;
  /** The date and time when the product was last indexed for search. */
  indexingDate?: Date | undefined;
  /** The maximum quantity of the product that can be purchased in a single order. A value of 0 indicates that there are no limitations on the maximum quantity. */
  maxQuantity?: number | undefined;
  /** The minimum quantity of the product that must be purchased in a single order. A value of 0 indicates that there are no limitations on the minimum quantity. */
  minQuantity?: number | undefined;
  /** Defines the number of items in a package. Quantity step for your product's. Default value is 1. */
  packSize?: number;
  /** First listed date and time. If you do not specify an end date, the product will be active until you deactivate it.If you do not specify an end date, the product will be active until you deactivate it.If you do not specify a start date, the product will become active immediately once you save it. */
  startDate?: Date;
  /** Listing expires on the specific date and time. If you do not specify an end date, the product will be active until you deactivate it. */
  endDate?: Date | undefined;
  /** The type of package for this product, which determines the product's specific dimensions. */
  packageType?: string | undefined;
  /** The unit of measurement for the product's weight. */
  weightUnit?: string | undefined;
  /** The weight of the product, in the unit specified by the WeightUnit property. */
  weight?: number | undefined;
  /** The unit of measurement for the product's height, length, and width. */
  measureUnit?: string | undefined;
  /** The height of the product, in the unit specified by the MeasureUnit property. */
  height?: number | undefined;
  /** The length of the product, in the unit specified by the MeasureUnit property. */
  length?: number | undefined;
  /** The width of the product, in the unit specified by the MeasureUnit property. */
  width?: number | undefined;
  enableReview?: boolean | undefined;
  /** The maximum number of times the product can be downloaded. A value of 0 indicates no limit. */
  maxNumberOfDownload?: number | undefined;
  /** The date and time when the download link or access to the product will expire. */
  downloadExpiration?: Date | undefined;
  /** The type of product download. Valid values include: "Standard Product", "Software", and "Music". */
  downloadType?: string | undefined;
  /** Indicates whether the product requires the user to agree to any terms or conditions before downloading. */
  hasUserAgreement?: boolean | undefined;
  /** Specifies the type of shipping option available for the product. */
  shippingType?: string | undefined;
  /** Specifies the type of tax applied to the product. */
  taxType?: string | undefined;
  /** ID of the vendor associated with the product. */
  vendor?: string | undefined;
  /** Indicates the position of the product in the catalog for ordering purposes. */
  priority?: number;
  /** An external identifier for the product that can be used for integration with external systems. */
  outerId?: string | undefined;
  properties?: Property[] | undefined;
  excludedProperties?: ExcludedProperty[] | undefined;
  /** Gets the default image for the product. */
  readonly imgSrc?: string | undefined;
  images?: Image[] | undefined;
  assets?: Asset[] | undefined;
  links?: CategoryLink[] | undefined;
  variations?: Variation[] | undefined;
  /** Each descendant type should override this property to use other object type for seo records */
  readonly seoObjectType?: string | undefined;
  seoInfos?: SeoInfo[] | undefined;
  reviews?: EditorialReview[] | undefined;
  associations?: ProductAssociation[] | undefined;
  referencedAssociations?: ProductAssociation[] | undefined;
  outlines?: Outline[] | undefined;
  /** System flag used to mark that object was inherited from other */
  readonly isInherited?: boolean;
  readonly parentCategoryIsActive?: boolean;
  relevanceScore?: number | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface CategoryLink {
  /** Entry identifier which this link belongs to */
  readonly entryId?: string | undefined;
  listEntryId?: string | undefined;
  /** Gets or sets the type of the list entry. E.g. "product", "category" */
  listEntryType?: string | undefined;
  /** Product order position in virtual catalog */
  priority?: number;
  catalogId?: string | undefined;
  categoryId?: string | undefined;
  /** Gets the Id of either target Catetory or Catalog */
  readonly targetId?: string | undefined;
  /** Gets the name of either target Catetory or Catalog */
  readonly name?: string | undefined;
  isAutomatic?: boolean;
}

export interface DynamicObjectProperty {
  objectId?: string | undefined;
  values?: DynamicPropertyObjectValue[] | undefined;
  name?: string | undefined;
  description?: string | undefined;
  objectType?: string | undefined;
  isArray?: boolean;
  isDictionary?: boolean;
  isMultilingual?: boolean;
  isRequired?: boolean;
  displayOrder?: number | undefined;
  valueType?: DynamicPropertyValueType;
  displayNames?: DynamicPropertyName[] | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface DynamicPropertyName {
  locale?: string | undefined;
  name?: string | undefined;
}

export interface DynamicPropertyObjectValue {
  objectType?: string | undefined;
  objectId?: string | undefined;
  locale?: string | undefined;
  value?: any | undefined;
  valueId?: string | undefined;
  valueType?: DynamicPropertyValueType;
  propertyId?: string | undefined;
  propertyName?: string | undefined;
}

export enum DynamicPropertyValueType {
  Undefined = "Undefined",
  ShortText = "ShortText",
  LongText = "LongText",
  Integer = "Integer",
  Decimal = "Decimal",
  DateTime = "DateTime",
  Boolean = "Boolean",
  Html = "Html",
  Image = "Image",
}

export interface EditorialReview {
  content?: string | undefined;
  reviewType?: string | undefined;
  languageCode?: string | undefined;
  isInherited?: boolean;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export enum EntryState {
  Detached = "Detached",
  Unchanged = "Unchanged",
  Added = "Added",
  Deleted = "Deleted",
  Modified = "Modified",
}

export interface ExcludedProperty {
  name?: string | undefined;
  isInherited?: boolean;
}

export interface IConditionTree {
  readonly id?: string | undefined;
  /** List of all available children for current tree node (is used in expression designer) */
  readonly availableChildren?: IConditionTree[] | undefined;
  readonly children?: IConditionTree[] | undefined;
}

export interface Image {
  binaryData?: string | undefined;
  altText?: string | undefined;
  relativeUrl?: string | undefined;
  url?: string | undefined;
  description?: string | undefined;
  sortOrder?: number;
  /** Gets or sets the asset type identifier. */
  typeId?: string | undefined;
  /** Gets or sets the asset group name. */
  group?: string | undefined;
  /** Gets or sets the asset name. */
  name?: string | undefined;
  outerId?: string | undefined;
  /** Gets or sets the asset language. */
  languageCode?: string | undefined;
  /** System flag used to mark that object was inherited from other */
  readonly isInherited?: boolean;
  readonly seoObjectType?: string | undefined;
  seoInfos?: SeoInfo[] | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface LocalizedString {
  readonly values?: { [key: string]: string } | undefined;
}

export interface OperationLog {
  objectType?: string | undefined;
  objectId?: string | undefined;
  operationType?: EntryState;
  detail?: string | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

/** Represents the path from the catalog to one of the child objects (product or category): catalog/parent-category1/.../parent-categoryN/object */
export interface Outline {
  /** Outline parts */
  items?: OutlineItem[] | undefined;
}

/** Represents one outline element: catalog, category or product. */
export interface OutlineItem {
  /** Object id */
  id?: string | undefined;
  /** Object type */
  seoObjectType?: string | undefined;
  /** All SEO records for the object */
  seoInfos?: SeoInfo[] | undefined;
  /** The name of current item */
  name?: string | undefined;
  localizedName?: LocalizedString | undefined;
  /** True when this object is linked to the virtual parent. */
  hasVirtualParent?: boolean;
}

export interface ProductAssociation {
  /** Association type (Accessories, Up-Sales, Cross-Sales, Related etc) */
  type?: string | undefined;
  priority?: number;
  quantity?: number | undefined;
  /** Is a primary key of associating object */
  itemId?: string | undefined;
  /** Each link element can have an associated object like Product, Category, etc.
Is a primary key of associated object */
  associatedObjectId?: string | undefined;
  /** Associated object type : 'product', 'category' etc */
  associatedObjectType?: string | undefined;
  outerId?: string | undefined;
  /** Display name for associated object */
  readonly associatedObjectName?: string | undefined;
  /** Associated object image URL */
  readonly associatedObjectImg?: string | undefined;
  tags?: string[] | undefined;
  readonly imgSrc?: string | undefined;
  images?: Image[] | undefined;
  id?: string | undefined;
}

export interface Property {
  /** Gets or sets a value indicating whether user can change property value. */
  isReadOnly?: boolean;
  /** Gets or sets a value indicating whether user can change property metadata or remove this property. */
  readonly isManageable?: boolean;
  /** Gets or sets a value indicating whether this instance is new. A new property should be created on server site instead of trying to update it. */
  isNew?: boolean;
  /** Gets or sets the catalog id that this product belongs to. */
  catalogId?: string | undefined;
  /** Gets or sets the category id that this product belongs to. */
  categoryId?: string | undefined;
  propertyGroupId?: string | undefined;
  name?: string | undefined;
  required?: boolean;
  dictionary?: boolean;
  multivalue?: boolean;
  multilanguage?: boolean;
  /** Gets or sets a value indicating whether this VirtoCommerce.CatalogModule.Core.Model.Property is hidden. */
  hidden?: boolean;
  valueType?: PropertyValueType;
  type?: PropertyType;
  outerId?: string | undefined;
  measureId?: string | undefined;
  ownerName?: string | undefined;
  displayOrder?: number | undefined;
  values?: PropertyValue[] | undefined;
  attributes?: PropertyAttribute[] | undefined;
  displayNames?: PropertyDisplayName[] | undefined;
  validationRules?: PropertyValidationRule[] | undefined;
  /** Represents property validation rules definition */
  readonly validationRule?: PropertyValidationRule | undefined;
  isInherited?: boolean;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface PropertyAttribute {
  propertyId?: string | undefined;
  value?: string | undefined;
  name?: string | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface PropertyDisplayName {
  name?: string | undefined;
  languageCode?: string | undefined;
}

export enum PropertyType {
  Product = "Product",
  Variation = "Variation",
  Category = "Category",
  Catalog = "Catalog",
}

/** Represents property validation rules definition */
export interface PropertyValidationRule {
  /** Uniquie value flag constrain */
  isUnique?: boolean;
  /** Down chars count border or null if no defined */
  charCountMin?: number | undefined;
  /** Upper chars count border or null if no defined */
  charCountMax?: number | undefined;
  /** Custom regular expression */
  regExp?: string | undefined;
  propertyId?: string | undefined;
  id?: string | undefined;
}

export interface PropertyValue {
  propertyName?: string | undefined;
  propertyId?: string | undefined;
  languageCode?: string | undefined;
  alias?: string | undefined;
  displayOrder?: number | undefined;
  valueType?: PropertyValueType;
  valueId?: string | undefined;
  value?: any | undefined;
  readonly propertyMultivalue?: boolean;
  outerId?: string | undefined;
  unitOfMeasureId?: string | undefined;
  colorCode?: string | undefined;
  isInherited?: boolean;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export enum PropertyValueType {
  ShortText = "ShortText",
  LongText = "LongText",
  Number = "Number",
  DateTime = "DateTime",
  Boolean = "Boolean",
  Integer = "Integer",
  GeoPoint = "GeoPoint",
  Html = "Html",
  Measure = "Measure",
  Color = "Color",
}

export interface QuoteAddress {
  id?: string | undefined;
  addressType?: AddressType;
  key?: string | undefined;
  name?: string | undefined;
  organization?: string | undefined;
  countryCode?: string | undefined;
  countryName?: string | undefined;
  city?: string | undefined;
  postalCode?: string | undefined;
  zip?: string | undefined;
  line1?: string | undefined;
  line2?: string | undefined;
  regionId?: string | undefined;
  regionName?: string | undefined;
  firstName?: string | undefined;
  middleName?: string | undefined;
  lastName?: string | undefined;
  phone?: string | undefined;
  email?: string | undefined;
  outerId?: string | undefined;
  isDefault?: boolean;
  description?: string | undefined;
}

export interface QuoteAttachment {
  name?: string | undefined;
  url?: string | undefined;
  mimeType?: string | undefined;
  size?: number;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface QuoteConfigurationItem {
  lineItemId?: string | undefined;
  productId?: string | undefined;
  name?: string | undefined;
  sku?: string | undefined;
  quantity?: number;
  imageUrl?: string | undefined;
  catalogId?: string | undefined;
  categoryId?: string | undefined;
  type?: string | undefined;
  customText?: string | undefined;
  files?: QuoteConfigurationItemFile[] | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface QuoteConfigurationItemFile {
  name?: string | undefined;
  url?: string | undefined;
  contentType?: string | undefined;
  size?: number;
  configurationItemId?: string | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface QuoteItem {
  currency?: string | undefined;
  listPrice?: number;
  salePrice?: number;
  sku?: string | undefined;
  productId?: string | undefined;
  product?: CatalogProduct | undefined;
  catalogId?: string | undefined;
  categoryId?: string | undefined;
  name?: string | undefined;
  comment?: string | undefined;
  imageUrl?: string | undefined;
  taxType?: string | undefined;
  quantity?: number;
  isConfigured?: boolean;
  selectedTierPrice?: TierPrice | undefined;
  proposalPrices?: TierPrice[] | undefined;
  configurationItems?: QuoteConfigurationItem[] | undefined;
  id?: string | undefined;
}

export interface QuoteRequest {
  sellerId?: string | undefined;
  sellerName?: string | undefined;
  readonly total?: number;
  number?: string | undefined;
  storeId?: string | undefined;
  channelId?: string | undefined;
  isAnonymous?: boolean;
  customerId?: string | undefined;
  customerName?: string | undefined;
  organizationName?: string | undefined;
  organizationId?: string | undefined;
  employeeId?: string | undefined;
  employeeName?: string | undefined;
  expirationDate?: Date | undefined;
  reminderDate?: Date | undefined;
  enableNotification?: boolean;
  isLocked?: boolean;
  status?: string | undefined;
  tag?: string | undefined;
  comment?: string | undefined;
  innerComment?: string | undefined;
  currency?: string | undefined;
  coupon?: string | undefined;
  manualShippingTotal?: number;
  manualSubTotal?: number;
  manualRelDiscountAmount?: number;
  totals?: QuoteRequestTotals | undefined;
  shipmentMethod?: ShipmentMethod | undefined;
  addresses?: QuoteAddress[] | undefined;
  items?: QuoteItem[] | undefined;
  attachments?: QuoteAttachment[] | undefined;
  operationsLog?: OperationLog[] | undefined;
  languageCode?: string | undefined;
  taxDetails?: TaxDetail[] | undefined;
  isCancelled?: boolean;
  cancelledDate?: Date | undefined;
  cancelReason?: string | undefined;
  readonly objectType?: string | undefined;
  dynamicProperties?: DynamicObjectProperty[] | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface QuoteRequestCondition {
  all?: boolean;
  not?: boolean;
  readonly id?: string | undefined;
  availableChildren?: IConditionTree[] | undefined;
  children?: IConditionTree[] | undefined;
}

export interface QuoteRequestSearchResult {
  totalCount?: number;
  results?: QuoteRequest[] | undefined;
}

export interface QuoteRequestTotals {
  originalSubTotalExlTax?: number;
  subTotalExlTax?: number;
  shippingTotal?: number;
  discountTotal?: number;
  taxTotal?: number;
  readonly adjustmentQuoteExlTax?: number;
  readonly grandTotalExlTax?: number;
  readonly grandTotalInclTax?: number;
}

export interface SearchQuoteRequestsQuery {
  sellerId?: string | undefined;
  number?: string | undefined;
  numberKeyword?: string | undefined;
  customerId?: string | undefined;
  organizationId?: string | undefined;
  storeId?: string | undefined;
  startDate?: Date | undefined;
  endDate?: Date | undefined;
  tag?: string | undefined;
  currency?: string | undefined;
  status?: string | undefined;
  statuses?: string[] | undefined;
  responseGroup?: string | undefined;
  objectType?: string | undefined;
  objectTypes?: string[] | undefined;
  objectIds?: string[] | undefined;
  keyword?: string | undefined;
  searchPhrase?: string | undefined;
  languageCode?: string | undefined;
  sort?: string | undefined;
  readonly sortInfos?: SortInfo[] | undefined;
  skip?: number;
  take?: number;
}

export interface SeoInfo {
  name?: string | undefined;
  semanticUrl?: string | undefined;
  outline?: string | undefined;
  pageTitle?: string | undefined;
  metaDescription?: string | undefined;
  imageAltDescription?: string | undefined;
  metaKeywords?: string | undefined;
  storeId?: string | undefined;
  organizationId?: string | undefined;
  objectId?: string | undefined;
  objectType?: string | undefined;
  isActive?: boolean;
  languageCode?: string | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface ShipmentMethod {
  shipmentMethodCode?: string | undefined;
  optionName?: string | undefined;
  logoUrl?: string | undefined;
  typeName?: string | undefined;
  currency?: string | undefined;
  price?: number;
}

export enum SortDirection {
  Ascending = "Ascending",
  Descending = "Descending",
}

export interface SortInfo {
  sortColumn?: string | undefined;
  sortDirection?: SortDirection;
}

export interface TaxDetail {
  rate?: number;
  amount?: number;
  name?: string | undefined;
}

export interface TierPrice {
  price?: number;
  quantity?: number;
}

export interface Variation {
  /** The type of product. Can be "Physical", "Digital", etc. */
  productType?: string | undefined;
  /** The Stock Keeping Unit (SKU) code for the product. */
  code?: string | undefined;
  /** A manufacturer part number (MPN) is a unique alphanumeric code assigned by a manufacturer to identify a specific product or component. It is used primarily for part tracking in inventory management, supply chain operations, and ordering purposes. */
  manufacturerPartNumber?: string | undefined;
  /** The Global Trade Item Number (GTIN) for the product. This can include UPC (in North America), EAN (in Europe), JAN (in Japan), and ISBN (for books). */
  gtin?: string | undefined;
  /** The name of the product. */
  name?: string | undefined;
  localizedName?: LocalizedString | undefined;
  /** The ID of the catalog to which this product belongs. */
  catalogId?: string | undefined;
  /** The ID of the category to which this product belongs. */
  categoryId?: string | undefined;
  /** Product outline in physical catalog (all parent categories ids concatenated. E.g. (1/21/344)) */
  readonly outline?: string | undefined;
  /** Product path in physical catalog (all parent categories names concatenated. E.g. (parent1/parent2)) */
  readonly path?: string | undefined;
  readonly titularItemId?: string | undefined;
  /** The ID of the main product associated with this product variation. */
  mainProductId?: string | undefined;
  /** Specifies whether the product is currently visible on the store for customers to view and purchase.
If set to false, the product is currently sold out. */
  isActive?: boolean | undefined;
  /** Specifies whether the product is currently visible on the store for customers to view and purchase.
If set to false, the product is currently ouf of stock. */
  isBuyable?: boolean | undefined;
  /** Indicates whether the inventory service is tracking the availability of this product.
If set to false, the product is considered in stock without any inventory limitations. */
  trackInventory?: boolean | undefined;
  /** The date and time when the product was last indexed for search. */
  indexingDate?: Date | undefined;
  /** The maximum quantity of the product that can be purchased in a single order. A value of 0 indicates that there are no limitations on the maximum quantity. */
  maxQuantity?: number | undefined;
  /** The minimum quantity of the product that must be purchased in a single order. A value of 0 indicates that there are no limitations on the minimum quantity. */
  minQuantity?: number | undefined;
  /** Defines the number of items in a package. Quantity step for your product's. Default value is 1. */
  packSize?: number;
  /** First listed date and time. If you do not specify an end date, the product will be active until you deactivate it.If you do not specify an end date, the product will be active until you deactivate it.If you do not specify a start date, the product will become active immediately once you save it. */
  startDate?: Date;
  /** Listing expires on the specific date and time. If you do not specify an end date, the product will be active until you deactivate it. */
  endDate?: Date | undefined;
  /** The type of package for this product, which determines the product's specific dimensions. */
  packageType?: string | undefined;
  /** The unit of measurement for the product's weight. */
  weightUnit?: string | undefined;
  /** The weight of the product, in the unit specified by the WeightUnit property. */
  weight?: number | undefined;
  /** The unit of measurement for the product's height, length, and width. */
  measureUnit?: string | undefined;
  /** The height of the product, in the unit specified by the MeasureUnit property. */
  height?: number | undefined;
  /** The length of the product, in the unit specified by the MeasureUnit property. */
  length?: number | undefined;
  /** The width of the product, in the unit specified by the MeasureUnit property. */
  width?: number | undefined;
  enableReview?: boolean | undefined;
  /** The maximum number of times the product can be downloaded. A value of 0 indicates no limit. */
  maxNumberOfDownload?: number | undefined;
  /** The date and time when the download link or access to the product will expire. */
  downloadExpiration?: Date | undefined;
  /** The type of product download. Valid values include: "Standard Product", "Software", and "Music". */
  downloadType?: string | undefined;
  /** Indicates whether the product requires the user to agree to any terms or conditions before downloading. */
  hasUserAgreement?: boolean | undefined;
  /** Specifies the type of shipping option available for the product. */
  shippingType?: string | undefined;
  /** Specifies the type of tax applied to the product. */
  taxType?: string | undefined;
  /** ID of the vendor associated with the product. */
  vendor?: string | undefined;
  /** Indicates the position of the product in the catalog for ordering purposes. */
  priority?: number;
  /** An external identifier for the product that can be used for integration with external systems. */
  outerId?: string | undefined;
  properties?: Property[] | undefined;
  excludedProperties?: ExcludedProperty[] | undefined;
  /** Gets the default image for the product. */
  readonly imgSrc?: string | undefined;
  images?: Image[] | undefined;
  assets?: Asset[] | undefined;
  links?: CategoryLink[] | undefined;
  variations?: Variation[] | undefined;
  /** Each descendant type should override this property to use other object type for seo records */
  readonly seoObjectType?: string | undefined;
  seoInfos?: SeoInfo[] | undefined;
  reviews?: EditorialReview[] | undefined;
  associations?: ProductAssociation[] | undefined;
  referencedAssociations?: ProductAssociation[] | undefined;
  outlines?: Outline[] | undefined;
  /** System flag used to mark that object was inherited from other */
  readonly isInherited?: boolean;
  readonly parentCategoryIsActive?: boolean;
  relevanceScore?: number | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface VcmpQuoteRequest {
  sellerId?: string | undefined;
  sellerName?: string | undefined;
  readonly total?: number;
  number?: string | undefined;
  storeId?: string | undefined;
  channelId?: string | undefined;
  isAnonymous?: boolean;
  customerId?: string | undefined;
  customerName?: string | undefined;
  organizationName?: string | undefined;
  organizationId?: string | undefined;
  employeeId?: string | undefined;
  employeeName?: string | undefined;
  expirationDate?: Date | undefined;
  reminderDate?: Date | undefined;
  enableNotification?: boolean;
  isLocked?: boolean;
  status?: string | undefined;
  tag?: string | undefined;
  comment?: string | undefined;
  innerComment?: string | undefined;
  currency?: string | undefined;
  coupon?: string | undefined;
  manualShippingTotal?: number;
  manualSubTotal?: number;
  manualRelDiscountAmount?: number;
  totals?: QuoteRequestTotals | undefined;
  shipmentMethod?: ShipmentMethod | undefined;
  addresses?: QuoteAddress[] | undefined;
  items?: QuoteItem[] | undefined;
  attachments?: QuoteAttachment[] | undefined;
  operationsLog?: OperationLog[] | undefined;
  languageCode?: string | undefined;
  taxDetails?: TaxDetail[] | undefined;
  isCancelled?: boolean;
  cancelledDate?: Date | undefined;
  cancelReason?: string | undefined;
  readonly objectType?: string | undefined;
  dynamicProperties?: DynamicObjectProperty[] | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(message: string, status: number, response: string, headers: { [key: string]: any }, result: any) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) throw result;
  else throw new ApiException(message, status, response, headers, null);
}

/* eslint-disable */
